project:
  type: book
  # change output-dir to "docs" to publish to gh pages
  output-dir: docs

book:
  title: "TMCA Urban Soil Mapping"
  author: "N.A. Jelinski, N.B. Pearson"
  date: "06-December-2023"
  cover-image: "TCMA-urban-soil-mapping-badge-13.png"
  
  chapters:
    - index.qmd
    - part: "Deliverables and Data Management"
      chapters:
      - deliverable1.qmd
      - deliverable2.qmd
      - deliverable3.qmd
      - deliverable4.qmd
      - datamanagementplan.qmd
    - part: "Discussion Log and Meeting Minutes"
      chapters:
      - minutes-15DEC2023-admin-kickoff.qmd
      - minutes-15DEC2023-technical-kickoff.qmd
      - minutes-12JAN2024-dsp.qmd
      - minutes-12JAN2024-qa-qc-nasis.qmd
      - minutes-02FEB2024-joe-nic-nora.qmd
      - minutes-02FEB2024-nic-nora.qmd
      - minutes-20FEB2024-patty-nic-nora.qmd
    # - authorship-guidelines.qmd
    - summary.qmd
    - references.qmd
  # appendices:
    # - co-authorship-template.qmd
    # - data-use-and-sharing.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual


