# TCMA Urban Soil Mapping Field Protocol

*Last edited 04SEP2024 NP*

## Sampling Location Selection

-   Complete the Pre-Sampling Survey on Survey123
-   Complete a site walk around and choose a sampling location.
    -   Look for electrical lines: either overhead or buried. If buried, they should be marked. As a best practice, find the electrical pole and the location that the pole connects to the house.
    -   Avoid sampling within three feet of a sidewalk, as utilities are commonly buried parallel to them.
    -   Check for detached buildings (garages, etc.) and look for signs of buried electrical lines from the house to the building. If there is a buried line, conduit will be visible coming from the ground and entering the detached building.
    -   The sampling location should be a representative area of the site and not highly disturbed in comparison to natural conditions. Keep in mind that this soil survey update is on a broader scale than the home level.
    -   In residential areas, do not sample in food-producing areas. Compost and other amendment applications are common and this does not represent the most common land use.
-   If sampling at a construction site: once location is established; place cones around the work area. Hard hats and high vis vests should be worn.

## Sampling Protocol

-   At sites where the ground surface is pavement (ie, a construction site where you are looking at an exposure), pavement should be included as a horizon. Do not start the description with the soil surface being the first horizon if there is pavement above it.
-   Auger to a minimum of 150 cm or until the auger handles are buried, carefully transferring each bucket into the gutter section.
    -   Pull the auger up after 2 full rotations to ensure that the soil is not compacted into the bucket.
    -   Take care to keep the depth of soil in the gutter the same as the depth of the whole. The tendency can be to expand the soil in the gutter. Compare the hole depth to the gutter depth after every 2 buckets by putting the auger all the way into the hole, putting a fist around the auger pole (with the bottom of the fist marking the ground depth), and comparing the length of the auger that was in the ground to the length of soil laying in the gutter.
-   Take detailed photos and videos of the profile in the gutter. This should be done prior to describing the profile to minimize disturbance. Use the spray bottle to re-moisten the profile if necessary.
    -   Lay a tape measure showing centimeters on one side of the gutter and a black fabric tape measure (“photo tape”) on the other side.
    -   Photos: Stand at the bottom of the gutter, hold the phone directly over the gutter (parallel to the gutter, not angled), and take a vertical photo of the entire profile. Also take vertical photos of 20 cm sections of the profile.
    -   Video: take a horizontal video while slowly moving from the top to the bottom of the profile.

## Profile Description Protocol

-   Delineate horizons after sampling using golf tees. Record horizon depths on the second page of the pedon description sheet using the tape measure, in centimeters. Complete the remainder of the second page.
    -   Use a Munsell color book to identify horizon colors. Record moist color for all horizons and dry color for surface or topsoil horizons.
    -   Record soil texture for each horizon.
    -   Estimate kind, percentage, and size of rock fragments.
    -   Identify horizon structure if possible; the auger may destroy natural structure, so be mindful of this.
    -   Estimate clay percent if possible, but disregard sand and silt percentages in the field.
    -   Describe redox features (red book page 2-12), ped & void surface features (2-32), and concentrations (2-20) if present.
    -   Describe pores and/or roots if present (2-70).
    -   Identify horizon names. This can also be done after the fact using profile photos.
    -   **Record sample codes in the boundaries column of the pedon description sheet.** Remember, codes should be the two digit year code and three digit sample code. Example: 24-123.
-   Complete the first page of the pedon description sheet (site level information, generally).
    -   Landscape and landform: remember to **record both the anthropogenic landscape and landform (e.g., urban anthroscape) in addition to the natural one.** See page 3-1 in the red book for complete lists for each.
    -   Slope %, using the clinometer
    -   Slope complexity
    -   Slope shape: up and down / across → 2 words, one for up/down and one for across. Choose from convex, concave, and linear.
    -   Drainage: estimate based on presence of redox features and soil texture.
    -   Flooding and ponding: make a note if either are present, otherwise leave blank
    -   Soil moisture status: very dry, dry, moist, very moist, wet (satiated or non-satiated). See red book for additional details.
    -   Parent material and bedrock can be done after the fact, but estimate parent material if possible. Remember, fill, if identified, is a different parent material.
    -   Erosion and runoff: can make notes if present, otherwise leave blank
    -   Surface stoniness: describe if present
    -   Any cells not included in above list can be left blank
-   Collect a soil sample from each horizon in a 5x8” ULINE bag labeled with sample code.
    -   Collect approximately 1 cup of soil, if possible; this should be just above the bottom line of the white box on the ULINE bags.

## Vegetation description protocol

-   Use the pedon description form to describe vegetation. It is acceptable to record the common name only, in the field.
    -   Only record species that compose greater than 2% of the visible area.
    -   Use iNaturalist’s [Seek](https://www.inaturalist.org/pages/seek_app) app for identification help.
    -   Always record percent cover of (1) bare soil and (2) litter or thatch (as opposed to live vegetation).
    -   Estimate: this should not take more than 5 minutes.

## Partial RUSI

-   Complete partial RUSI for the site using the field sheet, assigning each category a score between 0-3. Note that a higher score indicates a less urbanized area. See the backside of the sheet for descriptions of each category.
    -   Quantify traffic. Also note the size of the nearest road in the notes section.
    -   Quantify infrastructure.
    -   Quantify surface cover types. Specific species descriptions and percentages are included in the vegetation portion of the pedon description form.
    -   Quantify other soil characteristics, including texture, structure, etc.

## Post Sampling Protocol

-   Take a \~1 minute video of the site, in 0.5x if possible. Slowly walk around the site, narrating anything of importance. Highlight sampling location.
-   Take 6 photos of the site. Standing over or very near the auger hole, take photos facing north, east, south, and west away from the hole. Take a photo of your feet standing over or directly next to the hole. Take a photo approximately 10 feet away from the hole.
-   Take photos of the pedon description sheet.
-   Complete the Soil Observations & Pedon Descriptions survey in Survey123. Make sure that GPS coordinates are recorded. Upload site and pedon description sheet photos into the survey.
    -   All photos should be taken through the Camera app, not through Survey123; it compresses the photos and decreases the quality.
-   Upload scanned description sheet, pedon photos and video, and site photos and video to shared Google Drive folder
    -   Description sheets: folder titled "scanned-pedon-description-sheets"
    -   Pedon and site photos, site video: folder titled "site-photos-videos"
