# Joe, Nic, and Nora Check In

## Meeting Minutes

### Date: Tuesday, February 06, 2024

### Attendees:

-   Joseph Brennan (NRCS)\
-   Nic Jelinski (UMN)
-   Nora Pearson (UMN)

### Agenda:

-   Onboarding of Patty Burns (NRCS retiree)
-   Kickoff meeting planning
-   Investigation plan review
-   Resource planning

### Discussion Points:

#### Onboarding Patty Burns

-   Patty will be starting Feb 12th as a contractor for NRCS to support the project
-   She will be the main point of contact and lead for deliverables, given her extensive experience with NRCS urban soil mapping projects
-   Her time (16-20 hrs per pay period) is available to the UMN team - she can help with logistics, planning, project workflow, NRCS processes etc.
-   Joseph will connect with Patty every few weeks, but the UMN team can reach out to her directly as needed
-   Nora and Nic plan to have weekly check-ins with Patty to get her up to speed and seek guidance

#### Kickoff Meeting Planning

-   Original target was Q1 2023 but realistically looking at April/May now
-   U of MN team would like to have a more representative group beyond just NRCS, including:
    -   Municipal partners (City of Minneapolis, DNR, FWS, etc)
    -   Minnesota Geological Survey
    -   Grower groups
-   Joseph offered to check NRCS leadership availability the week of May 6th
-   Nic will send some date options that work for the UMN side
-   Goal is to find a common date in early May with NRCS leadership and external partners for a kickoff meeting over Zoom

#### Investigation Plan Review

-   Joseph noted that since this is an update rather than an initial survey, the documentation requirements are less intensive than some past urban projects
-   For raster projects, NRCS standards recommend 10 samples per map unit class as a minimum
-   Past urban projects like Detroit sampled around 300 sites for 200,000 acres
-   Joseph encouraged focusing on key properties needed by users - texture, organic matter, Ksat etc. - which can likely be estimated from existing data
-   The current agreement is for 3 field seasons, so recommendations are focused on the minimum requirements rather than extensive sampling
-   Nic agreed the DSP requirements seem achievable for the current scope

#### Resource Planning

-   Joseph estimates NRCS can commit around 50 staff weeks this first field season
-   This includes new soil scientist Adam Devlin starting in July who can commit 2-3 days per week
-   Other NRCS staff like Kellen, Clayton, Matt may also be able to assist periodically in the field
-   Nic suggested a broader spatial and temporal sampling plan over the next couple years, given the extra resources
-   The U of MN team can start developing a draft plan to share with NRCS in the coming weeks
-   Nora confirmed the U of MN side has capacity this season with her time plus opportunistic sampling

### Action Items:

-   UMN team to send some May kickoff meeting date options to Joseph
-   Joseph to check availability with NRCS leadership for early May kickoff meeting
-   Nora to connect with Patty Burns weekly once she starts Feb 12
-   UMN team to develop draft expanded sampling plan for next couple years
